This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (844 entries accepted, 0 rejected).
Sorting entries..........done (9754 comparisons).
Generating output file main.acr....done (300 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
