---
title: "Plot_generation_randomslopes"
author: "Disha Ghandwani"
date: "2024-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(latex2exp)
library(dplyr)
setwd("C:/Users/Disha Ghandwani/Dropbox/nsf_art_disha/random_slopes_ejs/plots")
```



```{r}
summaries_binded = read.csv('D:/randomslopes/simulations_results/diagonal_binded.csv')
logn=log10(summaries_binded$N)
```




```{r}
pdf(file="diag_estimation_time.pdf",width=8,height=5.5,pointsize=13)
par(mar=c(5.1,4.8,4.1,2.1))
plot(logn,log10(summaries_binded$max_lik_user_time),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($\log_{10}$ (Time complexity (in secs)))'),main="Estimation time",type="o",cex =0.5,ylim=c(0.2,3.5),xlim=c(3.2,6.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$moment_estimation_user_time+summaries_binded$backfitting_user_time),col="blue",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$moment_estimation_user_time+summaries_binded$var_backfitting_user_time),col="green",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$moment_estimation_user_time+summaries_binded$clubbed_var_backfitting_user_time),col="red",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$moment_estimation_user_time+summaries_binded$clubbed_backfitting_user_time),col="orange",type="o",cex =0.5, lwd = 2)
legend("topleft",legend=c("Backfitting","Clubbed backfitting","Clubbed variational EM","Variational EM", "lmer")
       ,col = c("blue","orange","red","green","black"),cex=1,lty=1, lwd = 3)
dev.off()

```


```{r}
pdf(file="diag_niter.pdf",width=7.6,height=5.5,pointsize=13)
par(mar=c(5.1, 4.1, 4.1, 10.1), xpd=TRUE)
plot(logn,log10(summaries_binded$niter_mle),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($\log_{10}$ (Number of iterations))'), main="Number of iterations",ylim = c(0.8,3.2),type="o",cex=0.5,xlim=c(3.2,6.2), cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)

lines(logn,log10(summaries_binded$niter_backfit),col="blue",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_var_backfit),col="green",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_clubbed_backfit),col="orange",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_clubbed_var_backfit),col="red",ty="o",cex=0.5, lwd = 2)
legend("topright",inset=c(-0.45,0),legend=c("Backfitting","Clubbed backfitting","Clubbed variational EM","Variational EM", "lmer")
       ,col = c("blue","orange","red","green","black"),cex= 1,lty=, lwd = 31)
dev.off()
```



```{r}
pdf(file="diag_sigma_ab.pdf",width= 10.4,height=9,pointsize=13)
par(mfrow=c(2,2))
par(mar=c(5.1,5.2,4.1,2.1))
sequence=-seq(1.6,2.8,0.20)
lst=c(1:4,7,9,12:13)
plot(logn,log10(summaries_binded$kl_err_Sigma_a_mom),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}$ KL divergence of $\hat{Sigma}_a)'),main=TeX(r'(Error in esimating ${Sigma}_a$ based on KL divergence)'),col="blue",xlim=c(3.2,6.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$kl_err_Sigma_a_mle),col="black",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$kl_err_Sigma_a_clubbed_var_backfit),col="red",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of moments", "lmer (maximum likelihood)", "Clubbed variational EM"),col = c("blue","black", "red"),cex=1,lty=1, lwd = 2)

plot(logn,log10(summaries_binded$kl_err_Sigma_b_mom),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}$ KL divergence of $\hat{Sigma}_b)'),main=TeX(r'(Error in esimating ${Sigma}_b$ based on KL divergence)'),col="blue",xlim=c(3.2,6.2), ylim = c( -3.5, 0.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$kl_err_Sigma_b_mle),col="black",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$kl_err_Sigma_b_clubbed_var_backfit),col="red",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of moments", "lmer (maximum likelihood)", "Clubbed variational EM"),col = c("blue","black", "red"),cex=1,lty=1, lwd = 2)

plot(logn,log10(summaries_binded$frob_err_Sigma_a_mom),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}(\|\hat{Sigma}_a-Sigma_a\|_F)$)'),main=TeX(r'(Error in esimating ${Sigma}_a$ based on frobenius norm)'),col="blue",xlim=c(3.2,6.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$frob_err_Sigma_a_mle),col="black",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$frob_err_Sigma_a_clubbed_var_backfit),col="red",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of moments", "lmer (maximum likelihood)", "Clubbed variational EM"),col = c("blue","black", "red"),cex=1,lty=1, lwd = 3)

plot(logn,log10(summaries_binded$frob_err_Sigma_b_mom),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}(\|\hat{Sigma}_b-Sigma_b\|_F)$)'),main=TeX(r'(Error in esimating ${Sigma}_b$ based on frobenius norm)'),col="blue",xlim=c(3.2,6.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$frob_err_Sigma_b_mle),col="black",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$frob_err_Sigma_b_clubbed_var_backfit),col="red",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of moments", "lmer (maximum likelihood)", "Clubbed variational EM"),col = c("blue","black", "red"),cex=1,lty=1, lwd = 3)
dev.off()
```





```{r}
pdf(file="diag_beta_sigma2e.pdf",width=13.5,height=5.5,pointsize=13)
par(mfrow=c(1,2))
par(mar=c(5.1,5.2,4.1,2.1))
plot(logn,log10(summaries_binded$err_beta_backfit),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($log_{10} (\|\hat{\beta}-\beta\|_2^2)$)'),main=TeX(r'(Error in estimating ${\beta}$)'),type="o",cex =0.5,xlim=c(3.2,6.2), col ="blue", lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$err_beta_clubbed_var_backfit),col="red", lwd = 2)
lines(logn,log10(summaries_binded$err_beta_mle),col="black",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Backfitting","Clubbed variational EM", "lmer")
       ,col = c("blue","red","black"),cex=1,lty=1, lwd = 3)


par(mar=c(5.1,5.2,4.1,2.1))
plot(logn,log10(summaries_binded$err_sigma2e_mom),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($log_{10} (|\hat{\sigma}^2_e/\sigma^2_e-1|)$)'),main=TeX(r'(Error in esimating ${sigma}^2_e$)'),type="o",cex =0.5,ylim = c(-3, -1),xlim=c(3.2,6.2), col ="blue", lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$err_sigma2e_mle),col="black",cex=0.5,ty="o", lwd = 2)
lines(logn,log10(summaries_binded$err_sigma2e_clubbed_var_backfit),col="red",ty="o",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of Moments","Clubbed variational EM", "lmer")
       ,col = c("blue","red","black"),cex=1,lty=1, lwd = 3)
dev.off()
```




```{r}
summaries_binded = read.csv('D:/randomslopes/simulations_results/non_diagonal_binded.csv')
logn=log10(summaries_binded$N)
```




```{r}
pdf(file="estimation_time.pdf",width=8,height=5.5,pointsize=13)
par(mar=c(5.1,4.8,4.1,2.1))
plot(logn[1:9],log10(summaries_binded$max_lik_user_time[1:9]),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($\log_{10}$ (Time complexity (in secs)))'),main="Estimation time",type="o",cex =0.5,ylim=c(0.2,4),xlim=c(3.2,6.2), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$backfitting_user_time),col="blue",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$var_backfitting_user_time),col="green",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$clubbed_var_backfitting_user_time),col="red",type="o",cex =0.5, lwd = 2)
lines(logn,log10(summaries_binded$clubbed_backfitting_user_time),col="orange",type="o",cex =0.5, lwd = 2)
legend("topleft",legend=c("Backfitting","Clubbed backfitting","Clubbed variational EM","Variational EM", "lmer")
       ,col = c("blue","orange","red","green","black"),cex=1,lty=1, lwd = 3)

dev.off()

```


```{r}
pdf(file="niter.pdf",width=7,height=5.5,pointsize=13)
par(mar=c(5.1, 4.8, 4.1, 13), xpd=TRUE)
plot(logn,log10(summaries_binded$niter_mle),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($\log_{10}$ (Number of iterations))'),main="Number of iterations to converge",ylim = c(0.8,3.2),type="o",cex=0.5,xlim=c(3.2,6.0), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)

lines(logn,log10(summaries_binded$niter_backfit),col="blue",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_var_backfit),col="green",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_clubbed_backfit),col="orange",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$niter_clubbed_var_backfit),col="red",ty="o",cex=0.5, lwd = 2)
legend("topright",inset=c(-0.82,0),legend=c("Backfitting","Clubbed backfitting","Clubbed variational EM","Variational EM", "lmer")
       ,col = c("blue","orange","red","green","black"),cex=1,lty=1, lwd = 3)
dev.off()
```



```{r}
pdf(file="sigma_ab.pdf",width=11.5,height=9,pointsize=13)
par(mfrow=c(2,2))
par(mar=c(5.1,5.2,4.1,2.1))
sequence=-seq(1.6,2.8,0.20)
lst=c(1:4,7,9,12:13)
plot(logn,log10(summaries_binded$kl_err_Sigma_a_clubbed_var_backfit),col="red",cex=0.5,xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",ylab=TeX(r'($log_{10}$ KL divergence of $\hat{Sigma}_a)'),main=TeX(r'(Error in esimating ${Sigma}_a$ based on KL divergence)'),xlim=c(3.2,6.0), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$kl_err_Sigma_a_mle),col="black",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("lmer (maximum likelihood)", "Clubbed variational EM"),col = c("black", "red"),cex=1,lty=1, lwd = 3)

plot(logn,log10(summaries_binded$kl_err_Sigma_b_clubbed_var_backfit),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}$ KL divergence of $\hat{Sigma}_b)'),main=TeX(r'(Error in esimating ${Sigma}_b$ based on KL divergence)'),col="red",xlim=c(3.2,6.0), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$kl_err_Sigma_b_mle),col="black",ty="o",cex=0.5, lwd = 2)
lines(logn,log10(summaries_binded$kl_err_Sigma_b_clubbed_var_backfit),col="red",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("lmer (maximum likelihood)", "Clubbed variational EM"),col = c("black", "red"),cex=1,lty=1, lwd = 3)

plot(logn,log10(summaries_binded$frob_err_Sigma_a_clubbed_var_backfit), xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}(\|\hat{Sigma}_a-Sigma_a\|_F)$)'),main=TeX(r'(Error in esimating ${Sigma}_a$ based on frobenius norm)'),col="red",xlim=c(3.2,6.0), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$frob_err_Sigma_a_mle),col="black",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("lmer (maximum likelihood)", "Clubbed variational EM"),col = c("black", "red"),cex=1,lty=1, lwd = 3)

plot(logn,log10(summaries_binded$frob_err_Sigma_b_clubbed_var_backfit),xlab = TeX(r'($\log_{10}(N)$)'),ty = "o",cex=0.5,ylab=TeX(r'($log_{10}(\|\hat{Sigma}_b-Sigma_b\|_F)$)'),main=TeX(r'(Error in esimating ${Sigma}_b$ based on frobenius norm)'),col="red",xlim=c(3.2,6.0), lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$frob_err_Sigma_b_mle),col="black",ty="o",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("lmer (maximum likelihood)", "Clubbed variational EM"),col = c("black", "red"),cex=1,lty=1, lwd = 3)
dev.off()
```





```{r}
pdf(file="beta_sigma2e.pdf",width=13.5,height=5.5,pointsize=13)
par(mfrow=c(1,2))
par(mar=c(5.1,5.2,4.1,2.1))
plot(logn,log10(summaries_binded$err_beta_backfit),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($log_{10} (\|\hat{\beta}-\beta\|_2^2)$)'),main=TeX(r'(Error in estimating ${\beta}$)'),type="o",xlim=c(3.2,6.0), col ="blue", lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$err_beta_clubbed_var_backfit),col="red", lwd = 2)
lines(logn,log10(summaries_binded$err_beta_mle),col="black",cex=0.5, lwd = 2)
op <- par(cex = 1)
legend("bottomleft",legend=c("Backfitting","Clubbed variational EM", "lmer")
       ,col = c("blue","red","black"),cex=1,lty=1, lwd = 3)


par(mar=c(5.1,5.2,4.1,2.1))
plot(logn,log10(summaries_binded$err_sigma2e_mom),xlab=TeX(r'($\log_{10}(N)$)'),ylab=TeX(r'($log_{10} (|\hat{\sigma}^2_e/\sigma^2_e-1|)$)'),main=TeX(r'(Error in esimating ${sigma}^2_e$)'),type="o",cex =0.5,,xlim=c(3.2,6.0),ylim=c(-3,-0.4), col ="blue", lwd = 2, cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5, cex.sub = 1.5)
lines(logn,log10(summaries_binded$err_sigma2e_mle),col="black",cex=0.5,ty="o", lwd = 2)
lines(logn,log10(summaries_binded$err_sigma2e_clubbed_var_backfit),col="red",ty="o",cex=0.5, lwd = 2)
legend("bottomleft",legend=c("Method of Moments","Clubbed variational EM", "lmer")
       ,col = c("blue","red","black"),cex=1,lty=1, lwd = 3)
dev.off()
```

```{r}
library(latex2exp)
ne = readRDS("../stitch_fix_results/stitch_fix_results_just_match_naiv_ineff.RDS")
naivety = ne$naivety
inefficiency = ne$inefficiency
pdf(file="naiv_ineff.pdf",width=10,height=5,pointsize=13)
par(mfrow=c(1,2))
hist(naivety,main=TeX(r'(Naivety of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,1}$)'),xlab="Naivety")
hist(inefficiency,main=TeX(r'(Inefficiency of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,1}$)'),xlab="Inefficiency")
dev.off()
pdf(file="naivety_inefficiency.pdf",width=8,height=5.5,pointsize=13)
plot(naivety,inefficiency,main=TeX(r'(Naivety and Inefficiency of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,1}$)'),col="blue",xlab="Naivety",ylab="Inefficiency")


```



```{r}
library(latex2exp)
ne = readRDS("../stitch_fix_results/stitch_fix_results_more_columns_naiv_ineff.RDS")
naivety = ne$naivety
inefficiency = ne$inefficiency
pdf(file="naiv_ineff_mc.pdf",width=10,height=5,pointsize=13)
par(mfrow=c(1,2))
hist(naivety,main=TeX(r'(Naivety of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,2}$)'),xlab="Naivety")
hist(inefficiency,main=TeX(r'(Inefficiency of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,2}$)'),xlab="Inefficiency")
dev.off()
pdf(file="naivety_inefficiency_mc.pdf",width=8,height=5.5,pointsize=13)
plot(naivety,inefficiency,main=TeX(r'(Naivety and Inefficiency of ${\hat{beta}}_{OLS}$ with respect to ${\hat{beta}}_{GLS,2}$)'),col="blue",xlab="Naivety",ylab="Inefficiency")


```

