$pdflatex = 'pdflatex %O %S; ps2pdf14 -dPDFSETTINGS=/prepress %B.pdf %B-embed.pdf; mv %B-embed.pdf %B.pdf';

add_cus_dep( 'tex', 'aux', 0, 'makeexternaldocument' );
 
sub makeexternaldocument {
    if (!($root_filename eq $_[0]))
    {
        system( "latexmk -pdf \"$_[0]\"" );
    }
}